### ISSUE TITLE
About Repository's Programming Language 

### ISSUE THREAD

**Issue by YigitDemirag** [e3e-monitor/e3e-detection-2016#1]
It's written as FORTRAN is the main language of this repo. Maybe we should correct it into C++?

**Comment by fakufaku** [comment]
Yeah, I noticed. This is because I checked in header files for FFTW so that we can easily deploy to new RPi devices. The headers are pretty big ^_^''

The files are in `pi_setup/`.

We could zip them if we want to avoid this.

**Comment by YigitDemirag** [comment]
Hmm. Therefore I think it is not that important for now. Thanks a lot for clarification :)
